### ISSUE TITLE
Wrong color for the style csWikipedia

### ISSUE THREAD

**Issue by quark67** [HugoPGomes/pgf-periodictable#2]
In the first column, the color used (for Li to Fr) is the old color. Also the color used for H, C, N, O, P, S, Se has changed from yellow to green. And color for elements 109 to 118 are not light gray yet on Wikipedia. And element At is yet yellow. The color displayed by the package:
<img width="741" alt="image" src="https://github.com/user-attachments/assets/b4aa1d60-ff44-4415-84dc-e0ba099c2998">

Yet, the color in the first column is more pale and color for H, C, N, O, P, S, Se is green (https://en.wikipedia.org/wiki/Periodic_table#Classification_of_elements)
<img width="613" alt="image" src="https://github.com/user-attachments/assets/c1d7e696-eb95-4126-a5c7-955ddf1a41ef">

On https://commons.wikimedia.org/wiki/File:Simple_Periodic_Table_Chart-en.svg we see the history for the periodic table displayed on Wikipedia.

<img width="1704" alt="image" src="https://github.com/user-attachments/assets/65f74e31-b0a2-4f27-9ee4-0235d76787c1">

As Wikipedia can change the color over time, perhaps the name of the theme must also contain a number version... `csWikipedia1`, `csWikipedia2`, `pgfPTWikipediaOne`, `pgfPTWikipediaTwo`...

**Comment by HugoPGomes** [comment]
Thanks for pointing it out. I'll update the package as soon as possible.

**Comment by HugoPGomes** [comment]
Solution implemented. The package will be updated as soon as possible.

**Comment by HugoPGomes** [comment]
Hi,
An update to pgf-PeriodicTable (v2.1.5 - 2025/02/10) has been submitted to
CTAN and two new color schemes have been added: 'csWikipediaI' and
'csWikipediaII'.
Thanks again,
Hugo Gomes

quark67 ***@***.***> escreveu (quarta, 11/09/2024 à(s) 11:10):
