### ISSUE TITLE
Legend Acronyms Font Adjustment

### ISSUE THREAD

**Issue by ajeducation** [HugoPGomes/pgf-periodictable#4]
What is the command to adjust the font size of legend acronyms?

**Comment by HugoPGomes** [comment]
In fact, there is no such option. The font size of legend acronyms is just the font size of the document.
I will work on it and it will be available in the next package update.
I appreciate the idea.

**Comment by HugoPGomes** [comment]
New key `legend acronyms font size` implemented. It will be available in the next package update as soon as I have time to include it in the documentation.

**Comment by HugoPGomes** [comment]
Hi,
An update to pgf-PeriodicTable (v2.1.5 - 2025/02/10) has been submitted to
CTAN and the requested features have been included.
Thanks again,
Hugo Gomes

ajeducation ***@***.***> escreveu (quarta, 30/10/2024 à(s)
12:28):
