### ISSUE TITLE
Empty Cells

### ISSUE THREAD

**Issue by ajeducation** [HugoPGomes/pgf-periodictable#5]
Hello, I liked your package a lot. Its great. I want to give my student an excercise, where a partial periodic table is printed. Say Z list={1,...,5,9,...,24}. In current scenerio cells 6,7,8 will not be printed. Is it possible that instead of no cell is drawn and no content is printed, empty cells are printed. So that students can be given excercise to fill the information about missing elements? 
1. can remaining cells of exercise list set to partticular scheme containing details of element as per \pgfPTbuildcellstyle.

**Comment by HugoPGomes** [comment]
Hi, I think it is possible to implement a solution to do it. Just to make sure I correctly understand the idea, I made the following schema:
![pgfPT_exList](https://github.com/user-attachments/assets/2a56481d-a9b9-4fe8-9935-a1b8bc56675b)

That is what you are thinking?
Best regards.

**Comment by ajeducation** [comment]
Absolutely, I want exactly this. Please describe setup

**Comment by HugoPGomes** [comment]
Ok. 
I have made the above scheme in Inkscape (editing the pdf file generated with pgf-PeriodicTable).
I will make the necessary changes to the package and submit an update as soon as possible.
Best regards

**Comment by ajeducation** [comment]
Much appreciated.👍

**Comment by HugoPGomes** [comment]
Extended syntax for the key `Z list` implemented.
For example:
````TeX
Z list=*{1,...,5,9,10,...24} 
````
or
````TeX
Z list=*({empty list options}){1,...,5,9,10,...24}
````
can be used to obtain a *Periodic Table* like the one shown above.
It will be available in the next package update as soon as I have time to include it in the documentation.

**Comment by HugoPGomes** [comment]
Hi,
An update to pgf-PeriodicTable (v2.1.5 - 2025/02/10) has been submitted to
CTAN and the requested features have been included.
Thanks again,
Hugo Gomes

ajeducation ***@***.***> escreveu (terça, 5/11/2024 à(s)
17:35):
